- name: Install Redis repository
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

- name: Enable Redis 6.2
  ansible.builtin.command: yum module enable redis:remi-6.2 -y
  changed_when: false  # Prevents Ansible from marking this task as changed every run

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present  # Use 'present' instead of 'installed' for consistency

- name: Allow remote connections to Redis
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '^bind 127.0.0.1'  # Ensures only the bind setting is changed
    replace: 'bind 0.0.0.0'

- name: Restart Redis to apply changes
  ansible.builtin.service:
    name: redis
    state: restarted

- name: Enable Redis service on boot
  ansible.builtin.service:
    name: redis
    enabled: yes