- name: Check if roboshop user exists
  ansible.builtin.command: id roboshop
  register: out
  ignore_errors: true

- name: Create roboshop user if not exists
  ansible.builtin.user:
    name: roboshop
  become: true
  when: out.rc is defined and out.rc != 0

- name: Check if /app directory exists
  ansible.builtin.stat:
    path: /app
  register: directory

- name: Print the directory stats
  ansible.builtin.debug:
    msg: "Output: {{ directory }}"

- name: Create /app directory if not exists
  ansible.builtin.file:
    path: /app
    state: directory
    owner: roboshop
    group: roboshop
    mode: '0755'
  become: true
  when: directory.stat.exists | default(false) == false

- name: Download {{ component }} artifact
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{ component }}.zip"
    dest: /tmp
  when: component is defined

- name: Extract {{ component }} artifact
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    owner: roboshop
    group: roboshop
    remote_src: yes
  become: true
  when: component is defined
