- name: copy {{component}} service
  ansible.builtin.copy:
      src: "{{component}}.service"
      dest: /etc/systemd/system/{{component}}.service

- name: deamon reload
  ansible.builtin.systemd:
      daemon_reload: true

- name: restart  {{component}} service
  ansible.builtin.service:
    name: {{component}}
    state: restarted
   
